View group forum
CrunchyBaguette/researchGroups pull request #31
Opened 2022-12-09 22:25 UTC by PANtroll

2022-12-09 23:02 UTC, CrunchyBaguette commented
![obraz](https://user-images.githubusercontent.com/68618094/206808451-f35e3df2-39c6-4b92-97b7-98b16c71e1e3.png)

Nwm czy nie zrobić większego limitu znaków, albo całkowicie go usunąć.

![obraz](https://user-images.githubusercontent.com/68618094/206808605-e480f6d5-63d6-400e-b332-e1d4c2bfc169.png)

Wystylizowałbym bardziej te przyciski, podobnie jak mamy w panelu koła naukowego i w panelu dodawania koła naukowego np.

![obraz](https://user-images.githubusercontent.com/68618094/206808708-07bc53d5-d38f-42b4-b627-fd4bebb93c0b.png)

Śmieszne, ale może nie na main takie coś. Dodatkowo pojawia się to na ułamek sekundy po naciśnięciu na powrót, nawet jak jest się członkiem:
![obraz](https://user-images.githubusercontent.com/68618094/206809142-4fa61560-5de4-4367-bf85-29cad8702618.png)
Chyba tutaj trzeba zamienić kolejnością:
```
this.isParticipant = data.isParticipant
this.loading = false
```

2022-12-09 23:15 UTC, Kamil-Lontkowski approved these changes

2022-12-09 23:19 UTC, Kamil-Lontkowski commented
Ogólnie ze stylem to trzeba będzie wszystko przerobić. Jeśli chodzi o limit znaków to wydaje mi się sensowny i chyba nie ma sensu tutaj dawać nielimitowanego.

Jak się korzysta z `queryset` to można później tego używać a nie `User.objects.filter` itd.... bo queryset jest cachowane więc nie będzie zawsze pobierał tego z bazy jeśli nie musi, więc jak masz w `queryset` `all()` a potem chcesz sobie to tylko przefiltrować to warto użyć `self.queryset`
No i musisz popatrzeć co nie przechodzi na CI

2022-12-12 10:35 UTC, CrunchyBaguette requested changes

2022-12-12 10:35 UTC, CrunchyBaguette commented on frontend/src/services/api.js
>  });
![obraz](https://user-images.githubusercontent.com/68618094/207021407-795ec9ef-a876-454e-8bf0-35ad2edd8144.png)
To sprawia, że użytkownik ani gość nie są w stanie zobaczyć żadnego katalogu

2022-12-12 10:35 UTC, CrunchyBaguette commented on frontend/src/components/forum/Post.vue
> +</template>
![obraz](https://user-images.githubusercontent.com/68618094/207023319-54eaf24f-104a-400d-98d1-6e16aaba3f4c.png)
Tego diva dodałbym jakiś margines na dole, bo ta treść jest zaraz na krawędzi

2022-12-12 10:35 UTC, CrunchyBaguette commented on frontend/src/components/forum/groupPost.vue
> +      </div>
Trzeba ustawić, że nie tylko autor ale i twórca koła albo moderator może usunąć posta.
- Edycja:
  - Autor
- Usuwanie:
  - Autor
  - Twórca koła/projektu
  - Moderator koła/projektu

2022-12-13 16:49 UTC, CrunchyBaguette commented
Twórca projektu nie może zobaczyć forum

2022-12-17 23:13 UTC, CrunchyBaguette commented
Ten branch był daleko w tyle jeśli chodzi o commity, i wystąpiły na początku konflikty z migracją.
Jak będziecie sprawdzać tą zmianę, to puśćcie migracje i zobaczcie, czy żadne errory wam nie wyjdą

2022-12-18 00:56 UTC, jaroslawwielgus commented
Migracje u mnie przechodzą.

Uwagi:
W przypadku forum dobrze jakby treść posta była widoczna od razu w tych kafelkach:
![obraz](https://user-images.githubusercontent.com/80279763/208271030-361cf908-78be-47e0-b858-5800bfd76173.png)

Przydałaby się paginacja jak w ogłoszeniach.

Brakuje białego boxa w forum projektu

Plus te pierdoły:
Przy edycji posta - jak zaakceptuje zmiany podając pustą treść to nic się nie dzieje – trzeba by zrobić to podobnie jak dla sekcji O Nas w kole (bo treść nie może być pusta).

![obraz](https://user-images.githubusercontent.com/80279763/208271949-b7453eab-175c-4b7a-906a-b2863de08d53.png)

I to samo tyczy się tytułu.

Czy też ten kwadracik macie:
![obraz](https://user-images.githubusercontent.com/80279763/208271084-d03b5b80-9f24-4c24-9e15-8881de7effce.png)

2022-12-18 01:18 UTC, jaroslawwielgus commented
Brakuje białego boxa w forum projektu
to must-have, reszta na koniec ewentualnie

2022-12-18 12:20 UTC, Kamil-Lontkowski commented on backend/projects/views.py
> +        postsQueryset = self.queryset.filter(project=project).order_by("added").all()
Tu chyba nie potrzebne jest to all()

2022-12-18 12:21 UTC, Kamil-Lontkowski commented on backend/research_groups/views.py
> +        postsQueryset = self.queryset.filter(research_group=researchGroup).order_by("added").all()
Tu tak samo z all()

2022-12-18 12:22 UTC, Kamil-Lontkowski requested changes
Trzeba naprawić CI

2022-12-18 12:23 UTC, Kamil-Lontkowski commented
I jeszcze na wszelki wypadek domergować main żeby nie nie zepsuć maina bo nie squashujemy commitów więc może być ciężko to cofnąć

2022-12-18 12:35 UTC, Kamil-Lontkowski commented
Są tu też zmiany w data-generator ale nadal się wysypuję w trakcie, może trzeba by było to ogarnąć żeby już było załatwione

2022-12-18 13:06 UTC, Kamil-Lontkowski commented
Chyba zjadło ikonki 
![image](https://user-images.githubusercontent.com/80274179/208300056-e22717e4-5843-458e-9ba8-4018ba88617b.png)

2022-12-18 13:08 UTC, Kamil-Lontkowski commented
Tu też jest nie symetrycznie
![image](https://user-images.githubusercontent.com/80274179/208300147-7fcb9041-f3cc-4b64-8db6-2f2b6b0104dc.png)

2022-12-18 20:55 UTC, Kamil-Lontkowski approved these changes

2022-12-18 22:59 UTC, Kamil-Lontkowski approved these changes

2022-12-18 22:59 UTC, CrunchyBaguette approved these changes

2022-12-18 23:00 UTC, merged